apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-vault
  namespace: {{ .Values.vault.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: gitlab
  namespace: {{ .Release.Namespace }}