apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-vault-setup
  annotations:
    argocd.argoproj.io/sync-wave: "3"       
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: vault-setup
  namespace: {{ .Release.Namespace }}